services:
  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
  nextjs:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres